- name: Kubesphere | Getting elasticsearch and curator installation files
  copy:
    src: "fluentbit-operator"
    dest: "{{ kubesphere_dir }}/"


# Upgrade or install fluent bit operator
- name: Kubesphere | Checking kubesphere-version
  shell: >
    {{ bin_dir }}/kubectl get deploy -n  kubesphere-system ks-console -o jsonpath='{.metadata.labels.version}'
  register: kubesphere_version
  ignore_errors: True


- name: Kubesphere | Prepare fluentbit operator setup
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/fluentbit-operator/init


- name: Kubesphere | Migrate fluentbit operator old config
  shell: >
    {{ bin_dir }}/kubectl apply -f  {{ kubesphere_dir }}/fluentbit-operator/migrator
  when:
    - kubesphere_version.stdout is version('v3.0.0', '<')


- name: Kubesphere | Deploy new fluentbit operator
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/fluentbit-operator/fluentbit
  register: import
  until: import is succeeded
  retries: 5
  delay: 3


# Update clusterconfig (cc) status
- name: Kubesphere | import fluentbit status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"fluentbit": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3