#  "/test" comment will reinstall KubeSphere in an open Pull Request.

name: Test-PullRequest

on:
  issue_comment:
    types: [created]

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
    - name: acknowledge deployment request to commenter
      id: check
      uses: khan/pull-request-comment-trigger@master
      with:
        trigger: "/test"
        reaction: rocket
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

  build-and-push:
    if: needs.deploy-check.outputs.triggered == 'true' or needs.test-check.outputs.triggered == "true"
    runs-on: ubuntu-latest
    needs: deploy-check
    steps:
    - name: get pull request ref
      id: get_pull_request_ref
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:repository/pulls/:issue_id
        repository: ${{ github.repository }}
        issue_id: ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@v2
      with:
        repository: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.repo.full_name }}
        ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}

    - name: Build image
      run: docker build . --file Dockerfile --tag kubespheredev/ks-installer:PRTEST

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: |
        echo "push image"
        docker push kubespheredev/ks-installer:PRTEST

  redeploy-kubesphere:
    needs: build-and-push
    working-directory: ${{env.working-directory}}
    runs-on: ubuntu-latest
    steps:
    - name: get pull request ref
      id: get_pull_request_ref
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:repository/pulls/:issue_id
        repository: ${{ github.repository }}
        issue_id: ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@v2

    - name: reinstall kubesphere
      run: |
        sh -x delete-kubespehre.sh && sh -x install.sh

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Congratulations! Deployment succeeded. This is the [preview link](http://${{ secrets.QING_PR_EIP }}:30880 }}/) .
        reactions: heart, hooray, laugh